---
# public IP of EC2 in dev.inv
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
      tags:
        - install
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
      tags:
        - start
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
      tags:
        - deploy
...
